# Generated by Django 2.0.5 on 2018-05-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0002_auto_20180525_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='mod',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
